export const initialProducts = [
  {
    id: 1,
    name: "Leriya Fashion Men's Regular Fit Shirt",
    category: "Clothing",
    price: 229.0,
    image: "https://www.bing.com/images/blob?bcid=r97VXWH9fYAHdhNXM9kxn.SNPedY.....4g",
    description: "High-quality cloth material with soft and comfortable fit for all-day.",
    brand: "Leriya Fashion",
  },
  {
    id: 2,
    name: "Knitted Square Neck T-Shirt Short Sleeve Tops",
    category: "Clothing",
    price: 339.0,
    image: "./assets/Product_2/image_1.jpg",
    description: "High-quality cloth material with soft and comfortable fit for all-day.",
    brand: "Sugathari Store",
  },
  {
    id: 3,
    name: "Naira Cut Kurta Set midi Dress",
    category: "Clothing",
    price: 449.0,
    image: "./assets/Product_3/image_1.jpg",
    description: "High-quality cloth material with soft and comfortable fit for all-day.",
    brand: "FlowerVelly",
  },
  {
    id: 4,
    name: "ZUVINO Formal Shirt Top for Women",
    category: "Clothing",
    price: 449.0,
    image: "./assets/Product_4/image_1.jpg",
    description: "High-quality cloth material with soft and comfortable fit for all-day.",
    brand: "ZUVINO Store",
  },
  {
    id: 5,
    name: "Lymio Casual Shirt for Men",
    category: "Clothing",
    price: 479.0,
    image: "assets/Product_5/image_1.jpg",
    description: "High-quality cloth material with soft and comfortable fit for all-day.",
    brand: "Lymio Store",
  },
  {
    id: 6,
    name: "Leriya Fashion Men Shirt",
    category: "Clothing",
    price: 319.0,
    image: "assets/Product_6/image_1.jpg",
    description: "High-quality cloth material with soft and comfortable fit for all-day.",
    brand: "Leriya Fashion",
  },
  {
    id: 7,
    name: "DHRUVI TRENDZ Women Rayon Clothing Set",
    category: "Clothing",
    price: 449.0,
    image: "assets/Product_7/image_1.jpg",
    description: "High-quality cloth material with soft and comfortable fit for all-day.",
    brand: "DHRUVI TRENDZ",
  },
  {
    id: 8,
    name: "COTLAND Fashions Breathable Cotton Printed A-Line Midi Dress for Women",
    category: "Clothing",
    price: 829.0,
    image: "assets/Product_8/image_1.jpg",
    description: "High-quality cloth material with soft and comfortable fit for all-day.",
    brand: "COTLAND Fashions",
  },
  {
    id: 9,
    name: "Pinkmint Popcorn Shirt",
    category: "Clothing",
    price: 829.0,
    image: "assets/Product_9/image_1.jpg",
    description: "High-quality cloth material with soft and comfortable fit for all-day.",
    brand: "Pinkmint Popcorn",
  },
  {
    id: 10,
    name: "GRECIILOOKS Men's Regular Fit Shirt",
    category: "Clothing",
    price: 829.0,
    image: "assets/Product_10/image_1.jpg",
    description: "High-quality cloth material with soft and comfortable fit for all-day.",
    brand: "GRECIILOOKS store",
  }
];
