export const initialProducts = [
  {
    id: 1,
    name: "Leriya Fashion Men's Regular Fit Shirt",
    category: "Clothing",
    price: 229.0,
    image: "https://i.pinimg.com/originals/69/20/f2/6920f212a7d4868e7263baacfaaa5649.jpg",
    description: "High-quality cloth material with soft and comfortable fit for all-day.",
    brand: "Leriya Fashion",
  },
  {
    id: 2,
    name: "Knitted Square Neck T-Shirt Short Sleeve Tops",
    category: "Clothing",
    price: 339.0,
    image: "https://th.bing.com/th/id/OIP.I3DvMxXKxLQW0Pu1UNBJZwHaFj?rs=1&pid=ImgDetMain",
    description: "High-quality cloth material with soft and comfortable fit for all-day.",
    brand: "Sugathari Store",
  },
  {
    id: 3,
    name: "Naira Cut Kurta Set midi Dress",
    category: "Clothing",
    price: 449.0,
    image: "https://img.freepik.com/premium-photo/blank-hoodie-mockup-template-with-hanger_441990-2023.jpg",
    description: "High-quality cloth material with soft and comfortable fit for all-day.",
    brand: "FlowerVelly",
  },
  {
    id: 4,
    name: "ZUVINO Formal Shirt Top for Women",
    category: "Clothing",
    price: 449.0,
    image: "https://img.freepik.com/premium-photo/blank-hoodie-mockup-template-with-hanger_441990-2012.jpg",
    description: "High-quality cloth material with soft and comfortable fit for all-day.",
    brand: "ZUVINO Store",
  },
  {
    id: 5,
    name: "Lymio Casual Shirt for Men",
    category: "Clothing",
    price: 479.0,
    image: "https://img.freepik.com/premium-photo/white-hoodie-mockup_863013-110032.jpg",
    description: "High-quality cloth material with soft and comfortable fit for all-day.",
    brand: "Lymio Store",
  },
  {
    id: 6,
    name: "Lymio Casual Shirt for Men",
    category: "Clothing",
    price: 479.0,
    image: "https://i.pinimg.com/564x/df/54/f1/df54f1c46d54a67f29fbc76f8f57f74d.jpg",
    description: "High-quality cloth material with soft and comfortable fit for all-day.",
    brand: "Lymio Store",
  },
];