export const initialProducts = [
  {
    id: 1,
    name: "Leriya Fashion Men's Regular Fit Shirt",
    category: "Clothing",
    price: 399.0,
    image: "https://i.pinimg.com/originals/69/20/f2/6920f212a7d4868e7263baacfaaa5649.jpg",
    description: "High-quality cloth material with soft and comfortable fit for all-day.",
    brand: "Leriya Fashion",
  },
  {
    id: 2,
    name: "Knitted Square Neck T-Shirt Short Sleeve Tops",
    category: "Clothing",
    price: 499.0,
    image: "https://th.bing.com/th/id/OIP.I3DvMxXKxLQW0Pu1UNBJZwHaFj?rs=1&pid=ImgDetMain",
    description: "High-quality cloth material with soft and comfortable fit for all-day.",
    brand: "Sugathari Store",
  },
  {
    id: 3,
    name: "Naira Cut Kurta Set midi Dress",
    category: "Clothing",
    price: 499.0,
    image: "https://img.freepik.com/premium-photo/blank-hoodie-mockup-template-with-hanger_441990-2023.jpg",
    description: "High-quality cloth material with soft and comfortable fit for all-day.",
    brand: "FlowerVelly",
  },
  {
    id: 4,
    name: "ZUVINO Formal Shirt Top for Women",
    category: "Clothing",
    price: 599.0,
    image: "https://img.freepik.com/premium-photo/blank-hoodie-mockup-template-with-hanger_441990-2012.jpg",
    description: "High-quality cloth material with soft and comfortable fit for all-day.",
    brand: "ZUVINO Store",
  },
  {
    id: 5,
    name: "Lymio Casual Shirt for Men",
    category: "Clothing",
    price: 679.0,
    image: "https://img.freepik.com/premium-photo/white-hoodie-mockup_863013-110032.jpg",
    description: "High-quality cloth material with soft and comfortable fit for all-day.",
    brand: "Lymio Store",
  },
  {
    id: 6,
    name: "Lymio Casual Shirt for Men",
    category: "Clothing",
    price: 999.0,
    image: "https://i.pinimg.com/564x/df/54/f1/df54f1c46d54a67f29fbc76f8f57f74d.jpg",
    description: "High-quality cloth material with soft and comfortable fit for all-day.",
    brand: "Lymio Store",
  },{
    id: 7,
    name: "STAR NASA Thick Aviator Jacket",
    category: "Clothing",
    price: 1299.0,
    image: "https://i.pinimg.com/564x/88/68/5f/88685ff42bc232465447b4411eb913b7.jpg",
    description: "Featuring a unique street lovers STAR NASA Thick Aviator Jacket design with cotton fabrication, which makes it stylish and comfortable.",
    brand: "Lymio Store",
  },{
    id: 8,
    name: "Autumn Embroidered Jacket Dragon Sukajan Jacket ",
    category: "Clothing",
    price: 1099.0,
    image: "https://i.pinimg.com/564x/ed/96/d5/ed96d59392b19254a158d3b659f44372.jpg",
    description: "Featuring a unique street lovers STAR NASA Thick Aviator Jacket design with cotton fabrication, which makes it stylish and comfortable.",
    brand: "Lymio Store",
  },{
    id: 9,
    name: "Golden Embroidered Sukajan Jacket ",
    category: "Clothing",
    price: 799.0,
    image: "https://i.pinimg.com/564x/64/1a/8a/641a8a9050688e48bc77943a2ead4224.jpg",
    description: "Featuring a unique street lovers STAR NASA Thick Aviator Jacket design with cotton fabrication, which makes it stylish and comfortable.",
    brand: "Lymio Store",
  },{
    id: 10,
    name: "Vintage Sukajan Jacket ",
    category: "Clothing",
    price: 899.0,
    image: "https://i.pinimg.com/564x/fa/f3/9e/faf39ecc2eed11e06285724adb99f612.jpg",
    description: "Featuring a unique street lovers STAR NASA Thick Aviator Jacket design with cotton fabrication, which makes it stylish and comfortable.",
    brand: "Lymio Store",
  },{
    id:11,
    name: "Chase Distressed Heavy Weight Oversized Fit T-Shirt",
    category: "Clothing",
    price: 1699.0,
    image: "https://overlaysnow.com/cdn/shop/files/Chase_1.jpg",
    description: "Featuring a unique street lovers STAR NASA Thick Aviator Jacket design with cotton fabrication, which makes it stylish and comfortable.",
    brand: "Overlays",
  },{
    id:12,
    name: "Panther Distressed Fade Heavy Weight Oversized T-Shirt",
    category: "Clothing",
    price: 1999.0,
    image: "https://overlaysnow.com/cdn/shop/files/Overlays-Edit-_1.jpg",
    description: "Featuring a unique street lovers STAR NASA Thick Aviator Jacket design with cotton fabrication, which makes it stylish and comfortable.",
    brand: "Overlays",
  }
];
